trigger:
- main

pool:
  name: hvlubuntu

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '8'
    addToPath: true

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'package'
